label q1:
    menu:
        "jelek"
        "ya":
            pass
        "tidak":
            pass
        "ga":
            pass
        "yessss":
            pass
    return
label q2:
    menu:
        "ganteng"
        "ga":
            pass
        "tidak":
            pass
        "yesn't":
            pass
        "kue":
            pass
    return
label q3:
    menu:
        "gemuk"
        "ddd":
            pass
        "ffff":
            pass
        "ddd":
            pass
        "aaaw3ffw":
            pass
    return
label q4:
    menu:
        "kurus"
        "aaaaaaa":
            pass
        "bbbbb":
            pass
        "bbbbb":
            pass
        "cccc":
            pass
    return
label q5:
    menu:
        "panjang"
        "fawfawf":
            pass
        "fawfwa":
            pass
        "afwafaw":
            pass
        "afwaf":
            pass
    return
